### ISSUE TITLE
plsdr will not start

### ISSUE THREAD

**Issue by imesg** [lutusp/PLSDR#4]
This is the result of an command line start:

> gene@go3:/usr/src/PLSDR# ./PLSDR.py 
Traceback (most recent call last):
  File "./PLSDR.py", line 32, in <module>
    from gnuradio import gr
ImportError: No module named 'gnuradio

gnuradio is installed. I need more clues.

Thanks for help

**Comment by imesg** [comment]
lutusp; I would like to revisit this problem. I use gentoo which allows the installation of several version of python i.e. I have four versions:

gene@go:/usr/src/PLSDR# eselect python list
Available Python interpreters, in order of preference:
  [1]   python3.6
  [2]   python3.4
  [3]   python3.5 (fallback)
  [4]   python2.7 (fallback)

So I changed all occurances of #!/usr/bin/env python to #!/usr/bin/env python2.7 because all python2.7 stuff is installed like this: /usr/lib64/python2.7/site-packages/osmosdr.

After doing this gnuradio module was found but:

gene@go:/usr/src/PLSDR# ./PLSDR.py
Traceback (most recent call last):
  File "./PLSDR.py", line 38, in <module>
    import osmosdr
  File "/usr/lib64/python2.7/site-packages/osmosdr/__init__.py", line 26, in <module>
    from osmosdr_swig import *
  File "/usr/lib64/python2.7/site-packages/osmosdr/osmosdr_swig.py", line 17, in <module>
    _osmosdr_swig = swig_import_helper()
  File "/usr/lib64/python2.7/site-packages/osmosdr/osmosdr_swig.py", line 16, in swig_import_helper
    return importlib.import_module('_osmosdr_swig')
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _osmosdr_swig

All of requirements are installed. Do you have any ideas how I can get this to run?

Thanks
