### ISSUE TITLE
Raspberry Pi audio sink topology failure

### ISSUE THREAD

**Issue by n7ihq** [lutusp/PLSDR#6]
Running PLSDR on the Raspberry Pi 3 with the default Audio Device setting produces the following error message:

gr::log :ERROR: audio_alsa_sink0 - [default]: set_channels failed: Invalid argument
Traceback (most recent call last):
  File "PLSDR.py", line 545, in run_stop_event
    self.run_stop()
  File "PLSDR.py", line 558, in run_stop
    self.start_process()
  File "PLSDR.py", line 537, in start_process
    self.radio.start()
  File "/usr/lib/python2.7/dist-packages/gnuradio/gr/top_block.py", line 109, in start
    top_block_start_unlocked(self._impl, max_noutput_items)
  File "/usr/lib/python2.7/dist-packages/gnuradio/gr/runtime_swig.py", line 5654, in top_block_start_unlocked
    return _runtime_swig.top_block_start_unlocked(r, max_noutput_items)
RuntimeError: check topology failed on audio_alsa_sink(49) using ninputs=1, noutputs=0
Aborted

This error is caused by the single input audio sink in PLSDR. The Raspberry Pi analog audio driver requires two input channels. A work around is changing the PLSDR Audio Device setting to hw:0,1. This uses the Raspberry Pi HDMI audio driver which accepts a single audio input channel. Changing the PLSDR code to add a second input to the audio sink would be a future solution to the problem.

Use the following PLSDR setup procedure:
Configure > Audio Device, enter: hw:0,1
Click quit (updates .PLSDR/config.ini file)
Restart PLSDR

If Raspberry Pi analog audio output is desired:
sudo raspi-config
Advanced Options > Audio > Force 3.5mm (‘headphone’) jack

**Comment by dave290** [comment]
Please clarify the following:

"Use the following PLSDR setup procedure:
Configure > Audio Device, enter: hw:0,1
Click quit (updates .PLSDR/config.ini file)
Restart PLSDR"

How do I access the setup procedure?  I tried "Configure" from a terminal window, but this isn't a recognized command.  Sorry, I'm new to this.  Thanks!

**Comment by dave290** [comment]
Please disregard my question.
